[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MedicalResonanceImaging = "93e74489-f9a4-430a-8db2-2b89ccbb1b9e"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Documenter = "1.10"
NLPModelsIpopt = "0.10"
NonlinearSolve = "4.6"
OptimalControl = "1.1"
OrdinaryDiffEq = "6"
Plots = "1.40"
Suppressor = "0.2"
julia = "1.10"
